package com.sample
 
import klasa.DrveniProzor;

 
import klasa.DrveniProzor.*;


rule "Ако је место живљења стан, а позиција стана исток или запад довољна је дебљина рама 68"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( mestoZivljenja == MestoZivljenja.stan && 
       (pozicija == Pozicija.istok || pozicija == Pozicija.zapad ))
    then
     
        dp.setDebljina(68);
        //dp.setBrojStakala(3);
        System.out.println("1.Pravilo");
        update( dp );
end

rule " Ако је спратност стана мања од 4, довољна је дебљина рама 68"
lock-on-active true
//salience 9
    when
       dp :  DrveniProzor( mestoZivljenja == MestoZivljenja.stan && spratnost < 4 )
    then
     
        dp.setDebljina(68);
    
        System.out.println("2.Pravilo");
        update( dp );
end

rule " Ако је дебљина рама 68, може само двослојно стакло"
no-loop true
//salience 10
   when
     dp :  DrveniProzor(brojStakala != 2 && debljina == 68)
   then
     
       dp.setBrojStakala(2);
    System.out.println("3.Pravilo");
      update( dp );
end
rule "Ако је спратност стана већа од 4 и мања од 15, довољна је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp :  DrveniProzor( mestoZivljenja == MestoZivljenja.stan && spratnost >= 4  && spratnost <= 15 )
    then
     
        dp.setDebljina(78);
    
        System.out.println("4.Pravilo");
        update( dp );
end

rule " Ако је спратност стана већа од 16, потребна је дебљина рама 90"
lock-on-active true
//salience 10
    when
       dp :  DrveniProzor( mestoZivljenja == MestoZivljenja.stan && spratnost >= 16 )
    then
     
        dp.setDebljina(90);
    
        System.out.println("5.Pravilo");
        update( dp );
end

rule "На основу позиције стана (југ), одређује се дебљина рама"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( mestoZivljenja == MestoZivljenja.stan && 
       pozicija == Pozicija.jug )
    then
     
        dp.setDebljina(78);

        System.out.println("6.Pravilo");
        update( dp );
end
rule "На основу позиције стана (север), одређује се дебљина рама"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( mestoZivljenja == MestoZivljenja.stan && 
       pozicija == Pozicija.sever )
    then
     
        dp.setDebljina(90);
       
        System.out.println("7.Pravilo");
        update( dp );
end

rule " Ако је дебљина рама прозора 78 или 90, може само трослојно стакло"
no-loop true
//salience 10
   when
     dp :  DrveniProzor(brojStakala != 3 && (debljina == 78 || debljina == 90))
   then
     
       dp.setBrojStakala(3);
    System.out.println("8.Pravilo");
      update( dp );
end

rule "На основу дебљине изолације (4), одређује се дебљина рама"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( mestoZivljenja == MestoZivljenja.kuca && fasada== true 
       && debljinaIzolacije == 4)
    then
     
        dp.setDebljina(68);
       
        System.out.println("9.Pravilo");
        update( dp );
end

rule "На основу дебљине изолације (8), одређује се дебљина рама"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( mestoZivljenja == MestoZivljenja.kuca && fasada== true 
       && debljinaIzolacije == 8)
    then
     
        dp.setDebljina(78);
       
        System.out.println("10.Pravilo");
        update( dp );
end



rule "На основу дебљине изолације (10), одређује се дебљина рама"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( mestoZivljenja == MestoZivljenja.kuca && fasada== true 
       && debljinaIzolacije == 10)
    then
     
        dp.setDebljina(90);
       
        System.out.println("11.Pravilo");
        update( dp );
end

rule "Ако корисник има грејање централно или нецентрализовано или конбиновано, а при томе живи на приморском подручју, довољна је дебљина рама 68 "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( podrucje == Podrucje.Primorskom && ( grejanje == Grejanje.centralno || grejanje == Grejanje.necentralizovano || grejanje == Grejanje.konbinovano)  )
    then
     
        dp.setDebljina(68);
       
        System.out.println("12.Pravilo");
        update( dp );
end

rule "Ако корисник има грејање централно и живи на планинском или брдцком подручју, потребна је дебљина рама 78”"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( grejanje == Grejanje.centralno && (podrucje == Podrucje.Brdskom || podrucje == Podrucje.Planinskom ))
    then
     
        dp.setDebljina(78);
       
        System.out.println("13.Pravilo");
        update( dp );
end
rule "Ако корисник има грејање нецентрализовано или конбиновано и живи на планинском или брдцком подручју, потребна је дебљина рама 90 "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( (grejanje == Grejanje.necentralizovano || grejanje == Grejanje.konbinovano ) && (podrucje == Podrucje.Planinskom || podrucje == Podrucje.Brdskom )) 
    then
     
        dp.setDebljina(90);
       
        System.out.println("14.Pravilo");
        update( dp );
end


rule "Ако корисник има грејање нецентрализовано и живи у равничарском подручју, потребна је дебљина рама 90 "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( grejanje == Grejanje.necentralizovano && 
       (podrucje == Podrucje.Ravnicarskom ) )
    then
     
        dp.setDebljina(90);
       
        System.out.println("15.Pravilo");
        update( dp );
end
rule "Ако корисник има грејање централно и живи у равничарском подручју, довољна је дебљина рама 68"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( grejanje == Grejanje.centralno && 
       (podrucje == Podrucje.Ravnicarskom ) )
    then
     
        dp.setDebljina(68);
       
        System.out.println("16.Pravilo");
        update( dp );
end
rule "Ако корисник живи на приморском подручју, систем ће постави материјал на неодређено(null)"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( podrucje == Podrucje.Primorskom   )
    then
     
        dp.setMaterijal(null);
       
        System.out.println("17.Pravilo");
        update( dp );
end

rule "Ако је осетљивост на буку и хладноћу= ДА и близина улице= ДА, потребна је дебљина рама 90"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Da" && osetljivostNaHladnocu == "Da"  && blizinaUlice == true)
    then
     
         dp.setDebljina(90);
       
        System.out.println("18.Pravilo");
        update( dp );
end


rule "Ако је осетљивост на буку и хладноћу = Слабија и (близина улице= ДА или близина улице= НЕ), довољна је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Slabije" && osetljivostNaHladnocu == "Slabije" &&(  blizinaUlice == true || blizinaUlice == false))
    then
     
         dp.setDebljina(78);
       
        System.out.println("19.Pravilo");
        update( dp );
end


rule "Ако је осетљивост на буку и хладноћу= НЕ и близина улице= НЕ, довољна је дебљина рама 68"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Ne" && osetljivostNaHladnocu == "Ne"  && blizinaUlice == false)
    then
     
         dp.setDebljina(68);
       
        System.out.println("20.Pravilo");
        update( dp );
end



rule "Ако је осетљивост на хладноћу= ДА остељивост на буку!= ДА и близина улице= НЕ, довољна је дебљина рама 78  "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaHladnocu == "Da" && osetljivostNaBuku != "Da" && blizinaUlice == false )
    then
     
         dp.setDebljina(78);
       
        System.out.println("21.Pravilo");
        update( dp );
end
rule "Ако је осетљивост на хладноћу= Слабија остељивост на буку!= Слабија и близина улице= ДА, а подручије!= Приморско, потребна је дебљина рама 90"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaHladnocu == "Slabije" && osetljivostNaBuku != "Slabije" &&(  blizinaUlice == true) && podrucje != Podrucje.Primorskom)
    then
     
         dp.setDebljina(90);
       
        System.out.println("22.Pravilo");
        update( dp );
end
rule "Ако је осетљивост на хладноћу= НЕ остељивост на буку!=НЕ и близина улице ДА, довољна је дебљина рама 78 "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaHladnocu == "Ne" && osetljivostNaBuku != "Ne" &&  blizinaUlice == true)
    then
     
         dp.setDebljina(78);
       
        System.out.println("23.Pravilo");
        update( dp );
end


rule "Ако је осетљивост на хладноћу!= ДА, а остељивост на буку= ДА и близина улице= НЕ, довољна је дебљина рама 78 "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Da" && osetljivostNaHladnocu != "Da"  && blizinaUlice == false )
    then
     
         dp.setDebljina(78);
       
        System.out.println("24.Pravilo");
        update( dp );
end
rule "Ако је осетљивост на хладноћу!= Слабија, а остељивост на буку= Слабија и близина улице или ДА или НЕ, довољна је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor(osetljivostNaBuku == "Slabije" &&  osetljivostNaHladnocu != "Slabije" &&(  blizinaUlice == true || blizinaUlice == false) )
    then
     
         dp.setDebljina(78);
       
        System.out.println("25.Pravilo");
        update( dp );
end
rule "Ако је осетљивост на буку= НЕ и хладноћу!= НЕ и близина улице= НЕ, довољна је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor(  osetljivostNaBuku == "Ne" && osetljivostNaHladnocu != "Ne" && (  blizinaUlice == false))
    then
     
         dp.setDebljina(78);
       
        System.out.println("26.Pravilo");
        update( dp );
end


rule "Ако је осетљивост на буку и хладноћу= Слабија и близина улице или ДА или НЕ, и живиу планинском подручју, потребна је дебљина рама 90"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaHladnocu == "Slabije" && osetljivostNaBuku == "Slabije" && blizinaUlice == true  && podrucje == Podrucje.Planinskom )
    then
     
         dp.setDebljina(90);
       
        System.out.println("27.Pravilo");
        update( dp );
end

rule "Ако је осетљивост на буку и хладноћу= ДА и близина улице или ДА или НЕ,  и живи на приморском подручју, довољна је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaHladnocu == "Da" && osetljivostNaBuku == "Da" && (  blizinaUlice == true || blizinaUlice == false) && podrucje == Podrucje.Primorskom )
    then
     
         dp.setDebljina(78);
       
        System.out.println("28.Pravilo");
        update( dp );
end

rule "Ако је осетљивост на буку и хладноћу= НЕ и близина улице или ДА или НЕ, и живи на планинском подручју или брдцком, довољна је дебљина рама 78 "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Ne" && osetljivostNaHladnocu == "Ne" &&  (  blizinaUlice == true ||  blizinaUlice == false) && (podrucje == Podrucje.Planinskom || podrucje == Podrucje.Brdskom))
    then
     
         dp.setDebljina(78);
       
        System.out.println("29.Pravilo");
        update( dp );
end


rule "Ако кућа нема фасаду, а налази се на подручју које није приморско и има грејање које није централно, потребна је дебљина рама 90"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( mestoZivljenja == MestoZivljenja.kuca && fasada== false
        && podrucje != Podrucje.Primorskom && grejanje != Grejanje.centralno )
    then
     
        dp.setDebljina(90);
       
        System.out.println("30.Pravilo");
        update( dp );
end
     

rule "Ако су димензије прозора 100х120, тип прозора је Једнокрилни"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor(  dimenzije == "100x120")
    then
     
         dp.setTip("Jednokrilni prozor");
       
        System.out.println("31.Pravilo");
        update( dp );
end


rule " Ако су димензије прозора 100х140, тип прозора је Једнокрилни "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor(  dimenzije == "100x140")
    then
     
         dp.setTip("Jednokrilni prozor");
       
        System.out.println("32.Pravilo");
        update( dp );
end
rule "Ако су димензије прозора 160х140, тип прозора је Двокрилни"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor(  dimenzije == "160x140")
    then
     
         dp.setTip("Dvokrilni prozor");
       
        System.out.println("33.Pravilo");
        update( dp );
end


rule "Ако је тип прозора Једнокрилни, дебљин рама 78, а мин цена >= 550, макс цена<= 800, систем ће предложити материјал Храст"
//lock-on-active true
no-loop true
//salience 10
    when
       dp : DrveniProzor(  tip == "Jednokrilni prozor" &&  debljina == 78 && (minCena  >= 550 && maxCena <=800))
    then
     
         dp.setMaterijal(Materijal.Hrast);
  
        System.out.println("34.Pravilo");
        update( dp );
end


rule "Ако је тип прозора Двокрилни, дебљин рама 78, а мин цена >= 550, макс цена<= 800, систем ће предложити материјал Храст" 
//lock-on-active true
no-loop true
//salience 10
    when
       dp : DrveniProzor(  tip == "Dvokrilni prozor" && debljina == 78 &&  (minCena  >= 550 && maxCena <=800) )             
    then
     
         dp.setMaterijal(Materijal.Hrast);
       
        System.out.println("35.Pravilo");
        update( dp );
end



rule "Ако корисник изабер друге дименнзије, тип и димензије се сетују на неодређено (null), да би систем из базе преложио рендом решења"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( dimenzije == "Druge")
    then
     
         dp.setTip(null);
         dp.setDimenzije(null);
        
        System.out.println("36.Pravilo");
        update( dp );
end

rule "Ако је тип прозора Једнокрилни, дебљин рама 90, а мин цена >= 550, макс цена<= 800, систем ће предложити материјал Храст"
//lock-on-active true
no-loop true
//salience 10
    when
       dp : DrveniProzor(  tip == "Jednokrilni prozor" && debljina == 90 &&  minCena  >= 550 && maxCena <=800 )           
    then 
     
         dp.setMaterijal(Materijal.Hrast);

        System.out.println("37.Pravilo");
        update( dp );
end


rule " Ако је тип прозора Једнокрилни, дебљин рама 68, а мин цена >= 550, макс цена<= 800, систем ће предложити материјал Храст "
//lock-on-active true
no-loop true
//salience 10
    when
       dp : DrveniProzor(  tip == "Jednokrilni prozor" && debljina == 68   && (minCena  >= 550 && maxCena <=800) )           
    then
     
         dp.setMaterijal(Materijal.Hrast);

        System.out.println("38.Pravilo");
        update( dp );
end
rule "Ако је тип прозора Двокрилни, дебљин рама 68, а мин цена >= 550, макс цена<= 800, систем ће предложити материјал Храст"
//lock-on-active true
no-loop true
//salience 10
    when
       dp : DrveniProzor(  tip == "Dvokrilni prozor" && debljina == 68 &&  (minCena  >= 550 && maxCena <=800) )             
    then
     
         dp.setMaterijal(Materijal.Hrast);

        System.out.println("39.Pravilo");
        update( dp );
end

rule "Ако је осетљивост на буку и хладноћу= НЕ и близина улице= ДА, довољна је дебљина рама 78 "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Ne" && osetljivostNaHladnocu == "Ne" &&  blizinaUlice == true )
    then
     
         dp.setDebljina(78);
       
        System.out.println("40.Pravilo");
        update( dp );
end
rule "Ако су димензије прозора 100х140 или 140х140 или 160х140, и ако је дебљина рама 90, постави дебљину на 0 , јер за ове димензије не постоји у бази ова дебљина рама"
//lock-on-active true
no-loop true
//salience 10
    when
       dp : DrveniProzor( (dimenzije == "100x140" || dimenzije == "140x140" || dimenzije == "160x140") && debljina == 90 )
    then
     
    dp.setDebljina(0);
       
        System.out.println("41.Pravilo");
        update( dp );
end


rule "Ако је осетљивост на буку и хладноћу= НЕ и близина улице= ДА, а кућа нема фасадну изолацију, налази се на подручју које није Приморско и грејање није централно, довољна је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Ne" && osetljivostNaHladnocu == "Ne" &&  blizinaUlice == true && fasada== false
        && podrucje != Podrucje.Primorskom && grejanje != Grejanje.centralno) 
    then
     
         dp.setDebljina(78);
       
        System.out.println("42.Pravilo");
        update( dp );
end


 rule "Osetljivost na buku = DA , a na hladnocu = Slabije ili NE i blizina ulice DA, potrebna je debljina rama 90cm    "
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Da" && ( osetljivostNaHladnocu != "Da" ) &&  blizinaUlice == true)
    then
     
         dp.setDebljina(90);
       
        System.out.println("43.Pravilo");
        update( dp );
end

rule "Ако је осетљивост на буку и хладноћу= ДА и близина улице= NE, потребна је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaBuku == "Da" && osetljivostNaHladnocu == "Da"  && blizinaUlice == false)
    then
     
         dp.setDebljina(78);
       
        System.out.println("44.Pravilo");
        update( dp );
end
rule "Ако корисник има конбиновано грејање и живи на равничарском подручју, довољна му је дебљина рама 78"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( grejanje == Grejanje.konbinovano && 
       (podrucje == Podrucje.Ravnicarskom ) )
    then
     
        dp.setDebljina(78);
       
        System.out.println("45.Pravilo");
        update( dp );
end
rule "Ако је осетљивост на хладноћу= ДА, а остељивост на буку= Слабија или НЕ и близина улице= ДА, а живи на подручју које није приморско, потребна је дебљина рама 90"
  
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaHladnocu == "Da" && osetljivostNaBuku != "Da" && blizinaUlice == true  && podrucje != Podrucje.Primorskom)
    then
     
         dp.setDebljina(90);
       
        System.out.println("46.Pravilo");
        update( dp );
end

rule "Ако корисник изабер мин цена >= 550 и  макс цена<= 800, онда их систем постави на 0 да би из базе приказао прозоре јефтиније од овог оквира"
lock-on-active true
//no-loop true
//salience 10
    when
       dp : DrveniProzor( minCena >= 550 && maxCena <= 800 )
    then
     
         dp.setMinCena(0);
         dp.setMaxCena(0);
       
        System.out.println("47.Pravilo");
        update( dp );
end

rule "Ако корисник живи на приморском подручју, а изабере мин цена >= 160 и  макс цена<= 375, онда систем предлаже за прозоре од материјала Јела"
lock-on-active true
//no-loop true
//salience 10
    when
       dp : DrveniProzor( podrucje == Podrucje.Primorskom  && minCena >= 160 && maxCena <= 375 )
    then
     
        dp.setMaterijal(Materijal.Jela);
       
        System.out.println("48.Pravilo");
        update( dp );
end

rule " Ако корисник изабере димензије прозора 100х120, а дебљина рама је различита од 90 и изабере мин цена >= 375 и  макс цена<= 550, онда систем постави мин и макс цену на 0 да би се из базе се приказали прозори јефтинији од овог оквира"
//lock-on-active true
no-loop true
//salience 10
    when
       dp : DrveniProzor(  dimenzije == "100x120" && debljina != 90 && minCena >= 375 && maxCena <= 550)
    then
     
    dp.setMinCena(0);
      dp.setMaxCena(0);
       
        System.out.println("49.Pravilo");
        update( dp );
end
rule " Ако корисник изабере димензије прозора 140х140, и изабере мин цена >= 375 и  макс цена<= 550, онда му систем предложи само прозоре типа Двокрилни "
lock-on-active true
//no-loop true
//salience 10
    when
       dp : DrveniProzor( dimenzije == "140x140" && minCena >= 375 && maxCena <= 550 )
    then
    
       dp.setTip("Dvokrilni prozor");
       
        System.out.println("50.Pravilo");
        update( dp );
end
rule "Ако је осетљивост корисника на хладноћу и буку= Слабија и близина улице= ДА, а има нецентрализовано грејање, и живи на подручју које није приморско, потребна је дебљина рама 90"
lock-on-active true
//salience 10
    when
       dp : DrveniProzor( osetljivostNaHladnocu == "Slabije" && osetljivostNaBuku == "Slabije"  && grejanje == Grejanje.necentralizovano && blizinaUlice == true  && podrucje != Podrucje.Primorskom )
    then
     
         dp.setDebljina(90);
       
        System.out.println("51.Pravilo");
        update( dp );
end